import { useState } from "react";
import { Menu, ChevronDown } from "lucide-react";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Button } from "@/components/ui/button";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

export default function Documentation() {
  const [activeSection, setActiveSection] = useState("Introduction");
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const sections = [
    { title: "Introduction", active: true },
    {
      title: "Quick Setup",
      subsections: ["Customization", "Video Tutorials", "Dark Mode"],
    },
    { title: "Build Assets" },
    { title: "Multi-demo" },
    { title: "File Structure" },
  ];

  const content: Record<string, { title: string; body: JSX.Element }> = {
    Introduction: {
      title: "Thank you for choosing TECH-AI",
      body: (
        <>
          <p className="mb-4">Dear Client</p>
          <p className="mb-4 text-muted-foreground leading-relaxed">
            We wanted to inform you that this documentation was generated by an Reveal Prompt as
            an example. While the content and structure of the documentation are based on best
            practices and industry standards, please note that it may not fully align with your
            specific requirements or project scope.
          </p>
          <p className="mb-4 text-muted-foreground leading-relaxed">
            The Reveal Prompt utilized advanced language processing capabilities to generate the
            documentation, incorporating information and guidelines commonly found in similar
            documentation. However, we strongly recommend reviewing and customizing the
            documentation to accurately reflect your project's unique needs, preferences, and
            implementation details.
          </p>
          <p className="mb-4 text-muted-foreground leading-relaxed">
            We understand the importance of tailored documentation that addresses your specific
            goals, and our team is more than happy to assist you in creating a comprehensive and
            customized documentation package. We will work closely with you to understand your
            project's intricacies and deliver documentation that precisely matches your
            expectations.
          </p>
          <p className="mb-4 text-muted-foreground leading-relaxed">
            Should you require any further assistance or have any questions regarding the
            documentation or any other aspect of your project, please feel free to reach out to
            our team. We are committed to providing you with the highest level of support and
            ensuring the success of your endeavor.
          </p>
          <p className="mb-4 text-muted-foreground leading-relaxed">
            Thank you for your understanding, and we look forward to collaborating with you
            further.
          </p>
          <div className="mt-8">
            <p className="text-muted-foreground">Best regards,</p>
            <p className="text-muted-foreground">Jack Nelson,</p>
            <p className="text-muted-foreground">Frenify</p>
          </div>
        </>
      ),
    },
    "Quick Setup": {
      title: "Quick Setup Guide",
      body: (
        <p className="text-muted-foreground leading-relaxed">
          Get started quickly with our comprehensive setup guide. This section covers everything
          you need to know to begin using the platform effectively.
        </p>
      ),
    },
    Customization: {
      title: "Customization Options",
      body: (
        <p className="text-muted-foreground leading-relaxed">
          Learn how to customize the platform to match your specific needs. From themes to
          advanced configuration options.
        </p>
      ),
    },
    "Video Tutorials": {
      title: "Video Tutorials",
      body: (
        <p className="text-muted-foreground leading-relaxed">
          Watch our step-by-step video tutorials to master the platform features quickly and
          efficiently.
        </p>
      ),
    },
    "Dark Mode": {
      title: "Dark Mode Configuration",
      body: (
        <p className="text-muted-foreground leading-relaxed">
          Enable and configure dark mode for a better viewing experience in low-light
          environments.
        </p>
      ),
    },
    "Build Assets": {
      title: "Build Assets",
      body: (
        <p className="text-muted-foreground leading-relaxed">
          Learn how to build and optimize assets for production deployment. This includes
          bundling, minification, and optimization strategies.
        </p>
      ),
    },
    "Multi-demo": {
      title: "Multi-demo Support",
      body: (
        <p className="text-muted-foreground leading-relaxed">
          Discover how to set up and manage multiple demo configurations for different use cases
          and audiences.
        </p>
      ),
    },
    "File Structure": {
      title: "File Structure",
      body: (
        <p className="text-muted-foreground leading-relaxed">
          Understanding the project's file structure is crucial for effective development. This
          guide explains the organization and purpose of each directory.
        </p>
      ),
    },
  };

  const currentContent = content[activeSection] || content.Introduction;

  const SidebarContent = () => (
    <div className="space-y-2">
      {sections.map((section, i) => (
        <div key={i}>
          {section.subsections ? (
            <Collapsible defaultOpen={activeSection === section.title || section.subsections.some(sub => sub === activeSection)}>
              <CollapsibleTrigger asChild>
                <Button
                  variant={activeSection === section.title ? "secondary" : "ghost"}
                  className="w-full justify-between hover:bg-muted"
                  onClick={() => {
                    setActiveSection(section.title);
                    setSidebarOpen(false);
                  }}
                >
                  <span>{section.title}</span>
                  <ChevronDown className="h-4 w-4" />
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent className="ml-4 mt-1">
                {section.subsections.map((sub, j) => (
                  <Button
                    key={j}
                    variant={activeSection === sub ? "secondary" : "ghost"}
                    className="w-full justify-start text-sm hover:bg-muted"
                    onClick={() => {
                      setActiveSection(sub);
                      setSidebarOpen(false);
                    }}
                  >
                    - {sub}
                  </Button>
                ))}
              </CollapsibleContent>
            </Collapsible>
          ) : (
            <Button
              variant={activeSection === section.title ? "secondary" : "ghost"}
              className="w-full justify-start hover:bg-muted"
              onClick={() => {
                setActiveSection(section.title);
                setSidebarOpen(false);
              }}
            >
              {section.title}
            </Button>
          )}
        </div>
      ))}
    </div>
  );

  return (
    <div className="flex h-screen lg:h-[calc(100vh-4rem)]">
      <div className="flex-1 flex flex-col bg-background overflow-y-auto">
        {/* Mobile header with menu */}
        <div className="p-3 sm:p-4 lg:hidden border-b border-border bg-background flex items-center justify-between sticky top-0 z-10">
          <h1 className="text-xl font-medium">Documentation</h1>
          
          <Sheet open={sidebarOpen} onOpenChange={setSidebarOpen}>
            <SheetTrigger asChild>
              <Button variant="outline" size="icon" className="flex-shrink-0">
                <Menu className="h-5 w-5" />
              </Button>
            </SheetTrigger>
            <SheetContent side="right" className="w-80 p-0 flex flex-col">
              <SheetHeader className="p-4 border-b border-border">
                <SheetTitle>Sections</SheetTitle>
              </SheetHeader>
              <div className="flex-1 overflow-y-auto p-6">
                <SidebarContent />
              </div>
            </SheetContent>
          </Sheet>
        </div>

        <div className="p-4 sm:p-8 lg:p-12">
          <h1 className="text-2xl sm:text-3xl flex justify-center font-medium mb-8 sm:mb-12 lg:mb-16 hidden lg:block">
            Documentation
          </h1>

          <div className="">
            <h2 className="text-xl sm:text-2xl font-medium mb-4 sm:mb-6">{currentContent.title}</h2>
            <div className="text-sm sm:text-base">{currentContent.body}</div>
          </div>
        </div>
      </div>

      {/* Desktop sidebar */}
      <aside className="hidden lg:flex w-80 border-l border-border p-6 bg-background overflow-y-auto flex-col">
        <SidebarContent />
      </aside>
    </div>
  );
}